set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Optional: -DARM_TOOLCHAIN_PATH=C:/tools/arm-gnu/bin or environment variable.
set(ARM_TOOLCHAIN_PATH "$ENV{ARM_TOOLCHAIN_PATH}" CACHE PATH "ARM GCC bin directory")
find_program(ARM_GCC arm-none-eabi-gcc HINTS "${ARM_TOOLCHAIN_PATH}")
if(NOT ARM_GCC)
    message(FATAL_ERROR "arm-none-eabi-gcc not found. Add its bin directory to PATH or set ARM_TOOLCHAIN_PATH.")
endif()
get_filename_component(ARM_BIN "${ARM_GCC}" DIRECTORY)
set(CMAKE_C_COMPILER "${ARM_GCC}")
find_program(ARM_GXX arm-none-eabi-g++ HINTS "${ARM_BIN}" REQUIRED NO_DEFAULT_PATH)
set(CMAKE_CXX_COMPILER "${ARM_GXX}")
set(CMAKE_ASM_COMPILER "${ARM_GCC}")
find_program(CMAKE_AR arm-none-eabi-ar HINTS "${ARM_BIN}" REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_RANLIB arm-none-eabi-ranlib HINTS "${ARM_BIN}" REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_OBJCOPY arm-none-eabi-objcopy HINTS "${ARM_BIN}" REQUIRED NO_DEFAULT_PATH)
find_program(CMAKE_SIZE arm-none-eabi-size HINTS "${ARM_BIN}" REQUIRED NO_DEFAULT_PATH)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
